### ISSUE TITLE
Social Media Promotion

### ISSUE THREAD

**Issue by SkyNerdT1** [phgelado/guardmypi#11]
We currently have a good presence on Facebook and LinkedIn. We need to start expanding this to other sites such as Twitter.

**Comment by SkyNerdT1** [comment]
Made a good start today on our Hackaday project: https://hackaday.io/project/178027-guardmypi

**Comment by SkyNerdT1** [comment]
Added some project logs to the Hackaday page.

**Comment by SkyNerdT1** [comment]
Will add a quick update to the hackaday page soon. @phgelado Have you added a project log for thee website to it?

**Comment by SkyNerdT1** [comment]
Now that the main program is ready for a pre-release I can add snippets of a saved video of each task doing as required (motion detection, facial recognition (unlocking) and QR detection (locking)

**Comment by SkyNerdT1** [comment]
@phgelado I think it would be beneficial to add the casting instructions to the Hackaday page as well!

**Comment by phgelado** [comment]
Demo video created and uploaded to Facebook, LinkedIn, Twitter and Hackaday!
