### ISSUE TITLE
InstaPush/Notification

### ISSUE THREAD

**Issue by SkyNerdT1** [phgelado/guardmypi#12]
Alerting the user if an intruder has entered their house

**Comment by SkyNerdT1** [comment]
I Will start looking at this next week. Been carried away with facial recognition.

**Comment by phgelado** [comment]
Possible way to do this through email? -> http://raspberrypiprogramming.blogspot.com/2014/09/send-email-to-gmail-in-c-with-boost-and.html

**Comment by MagnusBC98** [comment]
Achieved through Postfix mail protocol
