### ISSUE TITLE
Webcam Interface

### ISSUE THREAD

**Issue by SkyNerdT1** [phgelado/guardmypi#13]
Casting the feed from the Pi NoIR camera to the web app for the user to see.

**Comment by MagnusBC98** [comment]
Have had success with various methods but still need to figure out how to link it to our website

**Comment by phgelado** [comment]
https://randomnerdtutorials.com/video-streaming-with-raspberry-pi-camera/

**Comment by MagnusBC98** [comment]
Seems like the only way to do this is send opencv processed frames to server via sockets which may be tricky. Backup plan to save video files when intruder is detected has been designed

**Comment by phgelado** [comment]
@MagnusBC98 proposed saving the video files, and this was used as the basis for a workaround to implement the streaming via https://www.dataplicity.com/ to access the local 80 port of the raspberry pi from a web domain remotely and mjpg streamer https://github.com/jacksonliam/mjpg-streamer which allows to cast to the localhost images. The streaming implementation was integrated as follows -> saving image -> running mjpeg streamer to cast into port 80 -> use dataplicity to access this stream from the web.
