### ISSUE TITLE
Facial recognition using OpenCV FaceRecognizer - Fisherface/LBPH/Eigenface

### ISSUE THREAD

**Issue by SkyNerdT1** [phgelado/guardmypi#14]
Using the opencv_createsamples command I have started 2 training classifiers both with different levels of strictness

**Comment by SkyNerdT1** [comment]
The first classifier started raining on Friday (26/02/21):
![Screenshot from 2021-03-01 18-28-01](https://user-images.githubusercontent.com/53144690/109863902-1966cb00-7c5a-11eb-9acf-8e07cf807e96.png)

**Comment by SkyNerdT1** [comment]
The second classifier is making better progress currently : 
![Screenshot from 2021-03-03 19-54-51](https://user-images.githubusercontent.com/53144690/109864244-7ebabc00-7c5a-11eb-894d-b04e2607d22d.png)

**Comment by SkyNerdT1** [comment]
@MagnusBC98 What's the  status of the facial detection code?

**Comment by SkyNerdT1** [comment]
The HAAR cascade has finished training (1 week later) can't seem to pick up my face.

**Comment by MagnusBC98** [comment]
Closing this issue since it seems to be a dead end

**Comment by MagnusBC98** [comment]
Reopening since this is the approach we are going with again

**Comment by SkyNerdT1** [comment]
Can keep this issue open for now in case we bring in gesture detection to unlock the system.

**Comment by SkyNerdT1** [comment]
Started training the computer using the FisherFace recogniser class. Reasonable success with this method. Easy to implement confidence thresholds if the user is not detected. Will add photos to the training with different lighting scenarios as it is a downfall with this method. LBPH recogniser is not predicting my face correctly at all even with changing lighting and angles.

**Comment by SkyNerdT1** [comment]
Quick update, still good success picking up my face. Definitely varies with lighting and camera angles so good to implement other unlock features as well such as the QR code
