### ISSUE TITLE
Website 0.1 bugs, fixes, enhancements & tears

### ISSUE THREAD

**Issue by phgelado** [phgelado/guardmypi#16]
Updates required from 0.1 version -> https://www.guardmypi.com/

Our services update third card that says smart security - first card change "with it" to "it with"
You sent Today at 22:05
Add form action/data collection in "Register Your Interest"
You sent Today at 22:05
Integrate Pi casting server IP to Sign In button

**Comment by phgelado** [comment]
Add hackaday icon to footer social -> https://forkaweso.me/Fork-Awesome/icon/hackaday/ pointing to https://hackaday.io/project/178027-guardmypi

**Comment by phgelado** [comment]
For log in/persistent session use -> https://www.npmjs.com/package/react-session-persist

**Comment by phgelado** [comment]
Done -> Our services update third card that says smart security - first card change "with it" to "it with"
Done -> Add hackaday icon to footer social -> https://forkaweso.me/Fork-Awesome/icon/hackaday/ pointing to https://hackaday.io/project/178027-guardmypi

**Comment by SkyNerdT1** [comment]
Will go through the website thoroughly over the next couple of days. Looks great so far!

**Comment by phgelado** [comment]
Attempting implementation of authentication via Firebase and Routing -> https://www.youtube.com/watch?v=PKwu15ldZ7k
https://firebase.google.com/

**Comment by phgelado** [comment]
The website has now been updated to include a sign in, sign up, forgot password and update password features, implemented through Firebase Authentication. The code for this can be found in the "Website" branch. Next known steps/enhancements are: 
- Change "Sign In" button of Navbar to "Profile"  dashboard when user logged in 
- Add database feature where user can set up their own camera feed dataplicity link and access the casting
- Investigate minor bug where the update profile button from the Dashboard gives a 404
- Delete provisional/initial duplicated pages for sign in, sign up, etc...

**Comment by phgelado** [comment]
@SkyNerdT1 @MagnusBC98 feel free to mention any issues or bugs found in Alpha testing.
