### ISSUE TITLE
Create testing main

### ISSUE THREAD

**Issue by phgelado** [phgelado/guardmypi#2]
Create an alpha version of the final implementation that can call the three main processes motion detection -> pet detection -> facial detection to allow for testing in the sprints

**Comment by SkyNerdT1** [comment]
Part of this falls under the Motion and YOLO code integration.

**Comment by SkyNerdT1** [comment]
Because the facial recognition is part of another milestone I believe it should remain separate. Thoughts?

**Comment by SkyNerdT1** [comment]
Making a new branch that will be for integrating the code we have made in other branches and using threads. Also good cause we can then test a reactivation and stop function that kills the threads and loops back to the start.

**Comment by SkyNerdT1** [comment]
Currently myself and @MagnusBC98 have the main program running motion detection, facial recognition and hand detection. Currently trying to implement a timer in the Integration branch so that it only looks for a face 10s after it detects motion.

**Comment by SkyNerdT1** [comment]
The main program is now at a suitable level for a pre-release, the motion detection, facial recognition, QR Unlock and Lock now works. All there is to be added is the Pet detection which is as of now ready for integration.

**Comment by phgelado** [comment]
Alpha version 0.1 released.
