### ISSUE TITLE
Pet Detection 

### ISSUE THREAD

**Issue by phgelado** [phgelado/guardmypi#4]
Create CNN OpenCV pet detection with Oxford Pets Dataset

**Comment by phgelado** [comment]
Read through YOLO -> You Only Look Once implementation. Fast real-time capable classifier, might require reducing frame rate, original capability in Titan X GPU real-time at 45fps. 
https://learnopencv.com/deep-learning-based-object-detection-using-yolov3-with-opencv-python-c/ 
Original Paper -> https://arxiv.org/pdf/1506.02640.pdf

**Comment by MagnusBC98** [comment]
As for human detection, YOLO networks will not work on the Pi. We can potentially do some LBP training on this for dogs and cats at least, although there is already a Haar model for cat faces which we could use

**Comment by MagnusBC98** [comment]
Have trained an initial basic LBP cascade on Kaspar's (my dog's) face. It has been tested in real-time video and does detect his face though not totally reliably. A more thoroughly trained Haar cascade is probably required.

**Comment by phgelado** [comment]
@MagnusBC98 has taken the lead over this issue, it is currently at 80% just missing integration into main code

**Comment by MagnusBC98** [comment]
This has more or less been integrated, just need to discuss it at meeting on 08/04
