### ISSUE TITLE
Human Detection

### ISSUE THREAD

**Issue by MagnusBC98** [phgelado/guardmypi#8]
Code for detecting when a human enters the frame

**Comment by SkyNerdT1** [comment]
This code is completed, I believe we can close this issue and is now part of the next milestone for integrating with motion trigger

**Comment by MagnusBC98** [comment]
Reopening this, since it is now been done using cascade classifiers instead to let it run on the Pi.

**Comment by MagnusBC98** [comment]
Able to close this again since it has been updated using Haar cascades to allow for running on the Pi. The current implementation only detects a human's upper body but since there is no guarantee their full body will be in screen it is probably ok.
